version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/clojure:boot-2.7.2
  environment:
    JVM_OPTS: -Xmx3200m
    BOOT_JVM_OPTIONS: "-Xms512m -Xmx1024m"
    BOOT_WATCHERS_DISABLE: "yes"

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: project

      - run: boot test

      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: project

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: project
      - run: boot build-jar push-release

workflows:
  version: 2
  ci-workflow:
    jobs:
      - build
      - deploy:
          context: clojars
          requires:
            - build
          filters:
            branches:
              only:
                - master